### ISSUE TITLE
Rename the "easy" label

### ISSUE THREAD

**Issue by nikhita** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#188]
While contributing to open source projects, I have often noticed that what seems as "easy" to the developer working on the project is probably not that easy to me as a newcomer. And when I start working on an "easy" issue and face trouble, I feel demotivated that I am not qualified to solve even a simple issue.

Not sure if everyone feels like this or it's just me. ¯\\\_(ツ)\_/¯

I propose that we rename the "easy" label to something like "beginner".

Also, question: aren't "easy" and "first-timers-only" the same thing? If not, shouldn't they be? Shouldn't we be "saving" easy fixes for newcomers?

**Comment by vaibhavsingh97** [comment]
@nikhita I also think so but `easy` issues are easy and these issues are solvable by beginner but not by new commer/first timer. Also, new commer/first timer can pick easy issues. So can we can solve this issue by writing documentation just like [this](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html). Not this extensive guide but some sort of this so that developer can understand which labels are ment for what and how they can contribute to this repo.
@nikhita What are your opinion on this?
Btw I am up for that extensive guide for new commer guide 😄

**Comment by nikhita** [comment]
> So can we can solve this issue by writing documentation just like this.

Sounds awesome! We definitely need an effort in that direction. :+1: 

> I also think so but easy issues are easy and these issues are solvable by beginner but not by new commer/first timer. Also, new commer/first timer can pick easy issues.

Ok, I see how `easy` and `first-timers-only` can be mutually exclusive. However, I still feel that we should rename `easy` to `beginner`.

> easy issues are easy

This is easy (I made a pun, omg!) for us to say because we are familiar with the codebase but to someone new jumping in, it might not always be the case.

**Comment by tapaswenipathak** [comment]
Coool! We can have something like Difficulty: Easy, Difficulty: Medium, Difficulty: Hard; Type: Bug, Type: Enhancement, Type: Maintenance, Type: Question, Type: Testing with first-timers-only for the bot. 🎉

**Comment by tapaswenipathak** [comment]
Closing this, [updated the labels](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/labels).
