### ISSUE TITLE
Add wiki 

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#22]
Write about 
1. the project.
2. the branches.
3. how to install
4. any other information which makes it easier for someone to get started.

**Comment by Srijancse-zz** [comment]
Do you mean the github wiki, or a wiki for OSHC website?

**Comment by tapaswenipathak** [comment]
@Srijancse I mean the one we have on GitHub for repositories, for this, [here](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/wiki).

**Comment by Srijancse-zz** [comment]
Right. Got it!

**Comment by Logan1x** [comment]
i want to work on that. @tapasweni-pathak

**Comment by austinjcheng** [comment]
The wiki link just seems to redirect back to the main page. Any ideas on how to get started?

**Comment by tapaswenipathak** [comment]
@austinjcheng I didn't get your question. In this issue you have to write about the points that I have mentioned and add them to our wiki.

**Comment by Logan1x** [comment]
@tapasweni-pathak  when we go to 'wiki' section of repo that page redirect us to 'code' page. I think the same problem @austinjcheng having.

**Comment by nikhita** [comment]
@austinjcheng @Logan1x face the issue because you need to be a Github Org member to access the Wiki endpoint (https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/wiki). Else, it gets redirected to https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io.

Unfortunately, Github does not allow PRs for wikis. However, we can have a workaround to this.

A wiki is essentially a git repository in itself. So for our repo, the url would be `https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io.wiki.git`. 

What we can do:

- Create a new repo called OHSC-Wiki on our Github org.
- I'll clone the repo locally and replace the original "origin" remote with  `https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io.wiki.git`. 
- Add a few basic files to it so that new-comers can start off easily.
- We can now have PRs and issues on this repo. When the PRs are merged, the wiki will be updated automatically.

Further reading: https://help.github.com/articles/adding-and-editing-wiki-pages-locally/.

@tapasweni-pathak If this sounds good to you, I'll create the new repo and add the initial files + guidelines on how to edit the wiki. Then @austinjcheng and @Logan1x can split the tasks and contribute! :tada: 

I think this would be a good approach because:

1. Pull Requests - what can be better than this? :)
2. We can also create issues (which is not possible without this method).
3. I think this is a good issue for folks to work on. We should use this opportunity to the fullest and make it possible for them to contribute! :smile:

**Comment by Logan1x** [comment]
👍 @nikhita

**Comment by nikhita** [comment]
bump ^^ 
@amarlearning @vaibhavsingh97 @jarifibrahim should I go ahead with this?

**Comment by vaibhavsingh97** [comment]
@nikhita Create initial pages in wiki and let new comers make the first contribution by editing wiki :smile:

**Comment by jarifibrahim** [comment]
@nikhita 

> - We can now have PRs and issues on this repo. When the PRs are merged, the wiki will be updated automatically.

How will the commits from a completely different repository appear on this repo? When you change the *origin* remote it affects only your *local* copy. It has no effect on the original Github repo. I think someone with write access to `OpenSourceHelpCommunity.github.io` will have to fetch commits from the `OSHC-wiki` repo and then, push them to the `OpenSourceHelpCommunity.github.io.wiki.git` remote. 
However, we can automate this using Travis CI.

Please go ahead and create the new repo.

**Comment by nikhita** [comment]
@jarifibrahim Right, we'll probably have to automate this using Travis. :+1:

**Comment by nikhita** [comment]
I have created https://github.com/OpenSourceHelpCommunity/OSHC-Wiki.

A dummy wiki exists at https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/wiki because we need at least a first page to be able to clone the wiki. This dummy wiki will be overwritten by the real wiki later.

Further steps: enable travis on the new repo to make sure any changes merged in OSHC-Wiki are reflected in our main repo's wiki. It's quite late so I'll do it later.

If anyone wants to take a dig at this, please feel free to do so. You can find the instructions here: http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html. Note: You'll need access for this.

**Comment by tapaswenipathak** [comment]
@nikhita @jarifibrahim Do we need this now or it is already done?

**Comment by nikhita** [comment]
@tapasweni-pathak Not done yet. I can take a dig at this later this week.

But just to be clear, do we still want folks from outside the team editing the wiki? I can see the benefits in allowing to do so but am not so sure if it is really that useful anymore.

**Comment by tapaswenipathak** [comment]
Yes, we want to. We need writeups on how they installed and made it live in their local. We'll see later if need any changes there. Assigning this to you.

**Comment by tapaswenipathak** [comment]
:wave: @nikhita should we close this?

**Comment by nikhita** [comment]
Closing. We can reopen if needed later.
